# Change these first
owner: G6Tech # Your GitHub organization or username, where this repository lives
repo: upptime-cc # The name of this repository

sites:
  - name: Esus Formosa
    url: http://esus.formosa.carvalhoecunha.com.br:8080/esus

status-website:
  baseUrl: /upptime-cc
  name: Upptime
