# Change these first
owner: ahmcosta # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: site11
    url: http://54.166.88.8:80
  - name: site12
    url: http://54.166.88.8:81
  - name: site21
    url: http://54.221.110.227:80
  - name: site22
    url: http://54.221.110.227:81

status-website:
  baseUrl: /upptime
  name: Upptime
